export default [
  'Find the instructor who competed in guitar hero tournaments',
  'Find the instructor who is an award-winning actor/director',
  'Find the instructor who is a huge coffee nerd',
  'Find someone who has lived in more than 3 states',
  'Find someone who has lived abroad',
  'Find someone who loves working out',
  'Find someone who has more than one pet',
  'Find someone with the same favorite color as you',
  'Find someone who loves Texas summer',
  'Find someone who doesn\'t like chocolate',
  'Find someone who loves sugar too much',
  'Find someone who speaks another language',
  'Find someone who has a roommate',
  'Find someone who is left-handed',
  'Find out someone’s favorite sport',
  'Find someone who wears contact lenses',
  'Find out someone\'s favorite movie',
  'Find someone who has seen a wild bear or moose',
  'Find someone who doesn\'t eat meat',
  'Find someone who has traveled to more than ten states',
  'Find out what someone did over the weekend',
  'Find out someone\'s favorite local lunch place',
  'Find someone whose age is a prime number',
  'Find someone who is afraid of flying',
  'Find someone who meditates regularly',
  'Find someone who has slept on a beach overnight',
  'Find someone who can show you a magic trick',
  'Find someone who has changed a lightbulb in the last month',
  'Find someone who can play a musical instrument',
  'Find the youngest person in your cohort'
];