export default [
  'Brown eyes',
  'Green eyes',
  'Blue eyes',
  'Is an only child',
  'Has an older sibling',
  'Has a younger sibling',
  'Babysits for siblings',
  'Knows how to swim',
  'Was born in another country',
  'Parents do not speak English',
  'Speaks two languages',
  'Has bullied someone',
  'Has been bullied',
  'Has a family member in jail',
  'Has heard gun shots',
  'Lives with only one parent',
  'Lives with grandparents or aunts or uncles',
  'Adopted/foster care',
  'Has traveled out of the state',
  'Has lived in another state',
  'Has traveled out of the country',
  'Has been in a fight',
  'Knows somebody who has died from violence',
  'Has been to 2 or more schools',
  'Can cook food from their culture',
  'Is afraid of flying',
  'Wants to be an artist',
  'Meditates regularly',
  'Likes campfires',
  'Has slept on a beach overnight',
  'Can show you a magic trick',
  'Has milked a cow',
  'Has lived on a farm',
  'Is a Republican',
  'Is a Democrat',
  'Likes the Green party',
  'Has changed a lightbulb in the last month',
  'Knows what "Raku" is',
  'Knows what "Futoshiki" is',
  'Has a grandchild who believes in Santa',
  'Has been a camp counselor',
  'Was suspended from school',
  'Has been a teacher of any kind',
  'Wishes they were ruler of the world',
  "Doesn't have a Facebook page",
  'Has been in jail',
  'Goes to church/synagogue',
  'Volunteers',
  'Likes liver',
  'Is a tree hugger',
  'Was or still is a hippie',
  "Can tell you the name of Johnny Carson's sidekick",
  'Has won more than $1,000 in a lottery',
  'Has been on a game show',
  'Likes hiking in the woods',
  'Has seen a bear in the wilderness',
  'Has seen a moose in the wilderness',
  'Has piloted an airplane',
  'Has steered a motorboat',
  'Has been waterskiing',
  'Has gone camping completely alone',
  'Has hitchhiked',
  'Went to Woodstock',
  'Admits to using a plastic couch cover',
  'Knows who Howdy Doody was',
  'Watched an episode of the "Lawrence Welk" show when it was on TV',
  'Exercised to the "Jack LaLanne" show when it was on TV',
  'Can do a sun salutation',
  'Can play the fiddle',
  'Still has all their original teeth',
  'Has planted a tree',
  'Can bake a cake from scratch',
  'Without looking, can tell you what color socks they have on',
  'Can tell you what they dreamed last night',
  'Can name a character from "Star Trek"',
  'Has played Pokemon',
  "Still likes s'mores",
];